Shopify/themekit

commands/watch.go

I am not currently not writing any `go` code, so can't help out any further.
This is instead a huge thumbs up and thanks for version 0.1.0 works like a charm!

Fixes typo #29

---

theme_client.go

Use a byte buffer for uploads

---

commands/configure.go

Fixes bug shown in https://github.com/csaunders/themekit/issues/57
fyi @sinak

Fixes regression in configuration creation

---

cmd/theme/main.go
commands/download.go
commands/replace.go
commands/watch.go
theme_client.go
theme_event.go

Reduces the rate at which we are hitting the Shopify API
which could cause 429s to occur.
Fixes https://github.com/Shopify/themekit/issues/66
FIxes https://github.com/Shopify/themekit/issues/55

Improves error messages on 404s

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/fatih/color/.travis.yml
Godeps/_workspace/src/github.com/fatih/color/LICENSE.md
Godeps/_workspace/src/github.com/fatih/color/README.md
Godeps/_workspace/src/github.com/fatih/color/color.go
Godeps/_workspace/src/github.com/fatih/color/color_test.go
Godeps/_workspace/src/github.com/fatih/color/doc.go
Godeps/_workspace/src/github.com/mattn/go-isatty/LICENSE
Godeps/_workspace/src/github.com/mattn/go-isatty/README.md
Godeps/_workspace/src/github.com/mattn/go-isatty/doc.go
Godeps/_workspace/src/github.com/mattn/go-isatty/isatty_bsd.go
Godeps/_workspace/src/github.com/mattn/go-isatty/isatty_linux.go
Godeps/_workspace/src/github.com/mattn/go-isatty/isatty_windows.go
Godeps/_workspace/src/github.com/shiena/ansicolor/.gitignore
Godeps/_workspace/src/github.com/shiena/ansicolor/LICENSE
Godeps/_workspace/src/github.com/shiena/ansicolor/README.md
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor.go
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor/main.go
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor_ansi.go
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor_test.go
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor_windows.go
Godeps/_workspace/src/github.com/shiena/ansicolor/ansicolor_windows_test.go
Godeps/_workspace/src/github.com/shiena/ansicolor/example_test.go
Godeps/_workspace/src/github.com/shiena/ansicolor/export_test.go
utils.go

Fixes https://github.com/Shopify/themekit/issues/67

Use fatih/color for cross platform term color

---

cmd/theme/main.go
error_reporter.go

Fixes https://github.com/Shopify/themekit/issues/89

Exit immediately when the configuration is invalid

---

Makefile

We should have an easy way to run all the tests. With the creation of several sub-packages, we want to make it easier to add verify everything is still working.
This should also make it possible to add TravisCI support!
Please review @ilikeorangutans

Adds test task to makefile

---

Makefile
commands/configure.go
commands/download.go
commands/remove.go
commands/replace.go
commands/upload.go
file_watcher.go
file_watcher_test.go
simple_asset_event.go
theme/asset.go
theme/asset_test.go
theme/theme.go
theme_client.go
theme_client_test.go
theme_event.go
version.go

Fixed issue where error responses caused weird errors; moved `Theme` into `theme` package. 
@csaunders

Fixing non-ok responses

---

file_watcher.go

@csaunders @ilikeorangutans 
Quick fix to support some new folders we need for themes going forward.  Let me know if there's any updates needed for tests and the like.

expanded list of supported folders to include sections and blocks

---

CONTRIBUTORS

Adds an actual release process guide for the project

---

CONTRIBUTORS.md

fixes a typo and adds markdown

---

bucket/leaky_bucket.go
bucket/leaky_bucket_test.go

Realized that the leaky bucket could be rewritten without locks by harnessing the power of channels! :zap: 
@csaunders @chrisbutcher

Simplified leaky bucket

---

theme_client.go
theme_client_test.go

Just some golint-driven code style refactors
@ilikeorangutans for review

Minor theme_client* style changes

---

README.md

Adding Go Report card to README

---

Makefile

Added a help target with pretty output. All you need to do is add `## Description of target` after the target definition. 
Looks like this:
@chrisbutcher

Self documenting makefile

---

docs/index.html
install/index.html
nanoc/content/docs/index.md
nanoc/content/install/index.md
nanoc/content/stylesheet.css
stylesheet.css

To ship after https://github.com/Shopify/themekit/pull/145
@ilikeorangutans @stevebosworth @m-ux

Updating with access_token -> password docs terminology, other clarifications, formatting

---

commands/args.go
commands/version.go

These issues somehow weren't caught by the linter
cc: @ilikeorangutans

Fixing ConfigurationErrors issue, missed linting warning

---

Makefile

ref: https://github.com/mailgun/godebug
cc: @ilikeorangutans

Add 'make debug' to Makefile

---

.gitignore
Makefile

Woops, forgot to allow debug args
cc: @ilikeorangutans

Allowing debug args via make debug

---

file_watcher.go

No need for the block folder anymore
cc @Thibaut @stevebosworth

Remove block folder from asset locations

---

commands/upload.go
version.go

Fixes https://github.com/Shopify/themekit/issues/176 cc: @ilikeorangutans @cshold

Fix theme upload bug

---

docs/index.html
index.html
nanoc/Gemfile.lock
nanoc/content/docs/index.md

Fixes #117
@NathanPJF cc @Shopify/themes-fed

Add environment example to docs

---

cmd/theme/main.go
commands/args.go
commands/bootstrap.go
commands/configure.go
commands/download.go
commands/remove.go
commands/replace.go
commands/update.go
commands/upload.go
commands/upload_test.go
commands/version.go
commands/watch.go
configuration.go
theme_client.go
theme_client_test.go
version.go

Fixes https://github.com/Shopify/themekit/issues/180
To rebase and merge after https://github.com/Shopify/themekit/pull/155

Fix: Upload and other HTTP requesting commands don't report last asset affected

---

cmd/theme/main.go
commands/args.go
commands/version.go
configuration.go
version.go

cc: @ilikeorangutans to 🎩 
Aug 3: `timeout` can also be specified via config.yml

Fix timeout functionality, some commands can timeout, others cannot

---

cmd/theme/main.go

Fixes https://github.com/Shopify/themekit/issues/179
I thought I would start with an easy one to get familiar with the code base. This makes the help message print exactly the same every time. Thats all.

Deterministic Help Message

---

Makefile
README.md
circle.yml

Added CircleCI

---

Makefile

I added compiler flags and used upx to shrink our binary from 6.5M to 1.3M. This also remove stack traces that point to the machine that they were built on.

Adding build flags and upx packing

---

docs/index.html

Fixes https://github.com/Shopify/themekit/issues/182
Fixes https://github.com/Shopify/themekit/issues/186
I added some better documentation of the configuration on how to configure private apps to clear up that confusion.

Touching up docs.

---

cmd/theme/main.go
commands/watch.go
kit/environments.go
kit/theme_client.go
theme/asset_test.go
vendor/gopkg.in/yaml.v1/decode.go

Fixes https://github.com/Shopify/themekit/issues/156

Fixing -allenvs flag on watch

---

scripts/install

Adding the install script to the scripts directory on master so that it isn't in a branch that will get deleted because it is stale. 😆 
@chrisbutcher

Adding installer to scripts directory

---

commands/watch.go
kit/event_filter.go
kit/theme_client.go

Cleaned up the file watcher code a bit to use the theme clients filter and applied it to the asset lists from the server so that it filters downloads as well.
fixes https://github.com/Shopify/themekit/issues/126
cc @chrisbutcher @ilikeorangutans @jessicaxiejw

Ignored files apply to download

---

cmd/bootstrap.go
cmd/configure.go
cmd/download.go
cmd/remove.go
cmd/replace.go
cmd/theme.go
cmd/update.go
cmd/upload.go
cmd/version.go
cmd/watch.go
docs/_site/commands/index.html
docs/_site/configuration/index.html
docs/_site/development/index.html
docs/_site/feed.xml
docs/_site/ignores/index.html
docs/_site/index.html
docs/commands/index.md

Added documentation links to each of the command descriptions as well as fixing the flag documentation.
@chrisbutcher

Adding links to docs on command line.

---

cmd/download_test.go
cmd/theme_test.go
doc.go
kit/environments.go
kit/event_type.go
kit/theme_client_test.go
kit/version_test.go

Small linting for our report card

---

cmd/download.go
cmd/remove.go
cmd/replace.go
cmd/upload.go
cmd/watch.go
kit/configuration.go
kit/environments.go
kit/errors.go
kit/logging.go

Added one of the suggestions from #257 
I added the environment name to the logging for more clear operations.
```
[development]Asset Perform Update to README.md at host can-i-buy-a-feeling.myshopify.com
Status: 404 Not Found
Errors: This file is not part of your theme.
[development] Successfully performed Update on file assets/cart.svg.liquid from can-i-buy-a-feeling.myshopify.com
[development] Successfully performed Update on file templates/collection.liquid from can-i-buy-a-feeling.myshopify.com
```
@chrisbutcher

Added environment name to logging

---

cmd/open.go
cmd/theme.go
glide.lock
glide.yaml
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_test.go
vendor/github.com/skratchdot/open-golang/.gitignore
vendor/github.com/skratchdot/open-golang/LICENSE-MIT
vendor/github.com/skratchdot/open-golang/Makefile
vendor/github.com/skratchdot/open-golang/README.md
vendor/github.com/skratchdot/open-golang/open/exec.go
vendor/github.com/skratchdot/open-golang/open/exec_darwin.go
vendor/github.com/skratchdot/open-golang/open/exec_windows.go
vendor/github.com/skratchdot/open-golang/open/open.go
vendor/github.com/skratchdot/open-golang/open/open_test.go
vendor/github.com/skratchdot/open-golang/readme-template/package.txt
vendor/github.com/skratchdot/open-golang/vendor/xdg-open

Finishes up requests in #257 
Added an `theme open` command that was in the old ruby gem. It will open a browser link to preview the theme that is being worked on
@chrisbutcher 
I guess this means I have to update the version to `0.6.0` when I release this though. I didn't expect to get to 6 this fast.

Open command

---

cmd/bootstrap_test.go
fixtures/project/config.json
kit/asset_test.go
kit/configuration.go
kit/environments.go
kit/environments_test.go
kit/theme_client_test.go

fixes #263 
This added json support to config file loading.
@chrisbutcher

Adding json support for config files

---

cmd/replace.go
cmd/replace_test.go
cmd/theme.go
cmd/theme_test.go
cmd/upload.go
cmd/upload_test.go
kit/asset_test.go
kit/theme_client.go

fixes #171 
I have fixed this issue by asserting that the `settings_data.json` is uploaded absolutely after everything else is upload/replaced.
@chrisbutcher

Fixing sections upload order.

---

docs/_includes/sidebar.html
docs/commands/index.md

Adding open command documentation

---

docs/_includes/sidebar.html
docs/faq/index.md

@chrisbutcher 
Please check my grammar :P

Adding a FAQ page

---

docs/commands/index.md
docs/configuration/index.md

fixes #289 
fixes #290 
@chrisbutcher

Added default environemnt to the docs as well as fixed config docs

---

README.md
docs/_includes/header.html
docs/commands/index.md
docs/configuration/index.md
docs/development/index.md
docs/faq/index.md
docs/ignores/index.md
docs/index.md

@tanema for review
Most of this is pretty self-explanatory. The "OS X" => "macOS" change is due to Apple [re-branding their OS](http://www.apple.com/macos/sierra/) with the release of Sierra.

Tweaks to documentation - rewording, typo/capitalization fixes, etc.

---

cmd/bootstrap.go
cmd/bootstrap_test.go
cmd/theme.go
docs/commands/index.md

fixes #68 
These flags allow users to name their theme and use a custom theme url.
@chrisbutcher

Added a url and name flag to bootstrap

---

kit/errors.go
kit/errors_test.go

One of the fatal conditions was wrong but it would rarely get hit so I never noticed. I fixed this and added tests for the fatal conditions so this this doesn't happen again.
@chrisbutcher

Adding tests for errors

---

cmd/replace.go

Since replace acts like upload when there are filenames provided to it, I removed the code that did that operations and just passed the arguments to upload. This is in preparation to fix uploading with globs.

Refactored replace command

---

docs/configuration/index.md

Adding links to describe how to set env variables

---

cmd/theme/main.go

I have added the code and removed it several times (without configurability) so I could profile stuff before and I figured it was about time I just make it into good code and commited it so I could profile whenever I needed to. 
You can profile CPU usage and memory usages by setting the `THEMEKIT_CPUPROFILE` and `THEMEKIT_MEMPROFILE`  to a filepath.

Adding profiling functionality

---

cmd/update.go

Thanks to @tiffanytse for pointing out a typo.

Fixing typo in update command

---

cmd/open.go
cmd/theme.go

@chryton How about this. This will open the editor by calling `theme open -E` or `theme open --edit`

Added editor opening functionality

---

kit/environments.go

fixes #370 
This adds an error message for when the config is incorrectly indented.

Adding an error message to indicate a poorly formatted config

---

docs/_sass/custom/custom.scss

fixes #384 
There are a couple different ways to skin this cat but without retooling most of the sidenav this may be the most elegant.

Docs Navigation Overflow Fixes

---

kit/http_client.go
kit/rate_limiter.go
kit/rate_limiter_test.go

fixes #386 
This allows api calls to only be limited per domain. This means that processes that have multiple domains can be sped up because they are not as restricted.

Added functionality so that the api limit is only applied to each domain

---

cmd/replace.go
cmd/upload.go

I simplified the upload and replace actions so that the code is simpler and less redundant.

Took out some duplicate code 

---

scripts/install

Since I just updated the windows install script I thought I would update the install scripts for other systems. This simplifies it and makes it use the amazon cdn rather than the github releases.

Updated the install script to use cdn rather than github

---

cmd/file_manifest.go

fixes #442
There is a panic in the manifest while getting and writing to the manifest. I added in extra mutex around the problematic parts.

Adding mutex around missed cases

---

cmd/upload.go

It is too complex for me to explain... sorry.
Years of advanced deep research led me to believe this is the most appropriate approach.
You wouldn't understand if I tried to explain.
Of course not!

Typo fix at cmd/upload.go

---

cmd/upload_test.go

Fix a single test after a text change from a community PR

Fixing a test from a recent community pull request

---

docs/_config.yml
docs/_sass/custom/custom.scss
docs/commands/index.md
docs/faq/index.md
docs/index.md
docs/theme.lock/index.md

Updating Docs for missing items.
fixes #481

Updating documentation

---

kit/errors.go
kit/errors_test.go

Better 409 error

---

cmd/file_manifest.go

fixes #494 
It was unclear that the YAML errors were coming from problems with the manifest, this will correct this.

Better manifest loading errors

---

.github/CONTRIBUTING.md
Makefile
docs/_config.yml
docs/index.md

related: #541 
In the case of false positives of virus scanners saying that themekit is a virus, we can provide developers with checksums to ensure that the files are as expected.

Added checksums for download links

---

scripts/install.ps1

I was checking the checksum however I did nothing if it did not pass the check. This PR fixes that.

Fixing ps script

---

src/shopify/theme_client.go
src/shopify/theme_client_test.go

This didn't exactly work, it would output the error and delete the file however it did not create the new file

Fixing overwriting of compiled assets

---

cmd/watch.go

fixes https://github.com/Shopify/themekit/issues/489
This PR adds a semaphore to asset loading before uploading to prevent OOM errors. Since we now have a single location that assets are loaded before being uploaded, we can add a semaphore to ensure lower memory consumption. This should not slow down upload at all because the API limit comes into play long before this limit would.

Adding a semaphore to prevent memory errors

---

Makefile
scripts/install

Adding freebsd support

---

src/release/release.go

Version 1 0 0

---

cmd/deploy.go
cmd/theme.go

This just removes deprecated actions,

Removing deprecated actions

---

cmd/theme.go

Fix cmd typos

---

changelog.txt
docs/_includes/sidebar.html
docs/commands/index.md
docs/configuration/index.md
docs/index.md

Main changes to the docs
- Removing deprecated functions
- Removing useless documentation for util functions like `version`, `help`, `update`
- Adding in new documentation for the new `new` command
- Adding documentation for variable interpolation into the config.yml and the variable file for loading variables.

Preparing Docs For release

---

docs/scripts/install.py

related to #633 
This makes our install script more posix compliant. Very small change with very little effect

Make install script more posix-compliant

---

changelog.txt
src/file/path.go
src/file/path_test.go
src/release/release.go

This is adding support for sections-everywhere 😉

Sections everywhere

---

docs/index.md

Take out python installation from macOS

---

src/env/env.go

🛀 !== ./path ;)
@tanema @chrisbutcher

Simple typo fix

---

docs/configuration/index.md

Resolves #675
cc @tanema @chrisbutcher

Fix typo in Configuration docs

---

src/static/_testdata/theme-template/assets/application.js
theme-template/assets/application.js

Fix spelling error in comments in theme boilerplate javascript. 
https://github.com/Shopify/themekit/issues/677
@tanema 
@chrisbutcher

Fix typo in boilerplate code comments

---

docs/_includes/sidebar.html

- Use valid `fragment identifier` in the URL

Update sidebar link

---

docs/index.md

update placeholder store name to use consistent "your-store.myshopify.com"
cc: @tanema & @chrisbutcher

update placeholder store name

---

docs/commands/index.md

Originally reported by @ChrissBott in #666

Minor wording fix for README

---

src/httpify/client.go

@tanema Just confirming there isn't some other `doJSON` method this is referring to?

Fix incorrect `doJSON` comment

---

cmd/deploy_test.go
cmd/download.go
cmd/watch.go
src/colors/colors.go

As agreed with @Nupur-Mukherjee .
Fixes #728

Minor UX tweaks

---

src/shopify/theme_client.go

Fix some minor typos in comments

---

.github/CONTRIBUTING.md
changelog.txt
src/release/release.go

Prepare release for 1.1.0-beta

---

changelog.txt
src/release/release.go

Prepare 1.1.0 beta2 release

---

.github/CONTRIBUTING.md

Add tip about using themekit_dump

---

docs/index.md

Update docs for private app development

---

docs/commands/index.md

This shouldn't be merged until we're ready to release the updated themekit with checksum support, and the beta flag added in https://github.com/Shopify/shopify/pull/251785 is removed.

Update docs for checksums

---

docs/faq/index.md

Update FAQ heading grammar

---

CONTRIBUTING.md

Clarify homebrew-shopify update instructions

---

README.md

This repo is no longer maintained by just the 3 original contributors so we can remove this.

Removing contributors from readme

---

docs/index.md

Updated the Get API Access section to add more context for the new 'Enable private app development' feature

Added details + links to more context for private apps

---

changelog.txt
choco/themekit.nuspec
choco/tools/chocolateyinstall.ps1
docs/_config.yml
src/release/release.go

Prepare v1.1.2 release

---

cmd/configure.go
cmd/deploy.go
cmd/download.go
cmd/get.go
cmd/new.go
cmd/publish.go
cmd/remove.go
cmd/theme.go
cmd/watch.go

fixes #817
We want to add consistency to all links. for this, we changed
`http` to `https`.

Update links with https

---

docs/ignores/index.md

Update docs regarding windows `ignore_files` settings

---

docs/index.md

Add reference to node themekit in the docs

---

changelog.txt
src/release/release.go

Release 1.1.4

---

changelog.txt
src/release/release.go

Releasing 1.1.5

---

docs/_config.yml

Docs release v1.1.5

---

src/cmdutil/util.go

fixes https://github.com/Shopify/themekit/issues/639

Allow env vars to be used in get and new

---

docs/scripts/install.py

For https://github.com/Shopify/themekit/issues/896

Restore install script in original location

---

cmd/configure.go
cmd/deploy.go
cmd/download.go
cmd/get.go
cmd/new.go
cmd/publish.go
cmd/remove.go
cmd/watch.go

Noticed these links were broken

Fix shopify.dev links

---

.travis.yml
README.md

remove_codecov

---

changelog.txt
src/release/release.go

Update version for Theme Kit Access messaging

---

theme-template/assets/application.css.liquid

CSS comment instead of JS comment

---

README.md

Making the deprecation official.

Theme Kit Deprecation notice
