Shopify/themekit

cmd/theme/main.go, commands/upload.go, event_filter.go, event_filter_test.go, file_watcher.go, theme_client.go, theme_client_test.go, theme_event.go
This fixes upload such that a request to upload will upload all files instead of having to specify the exact files.
- Also fixes a bug with git repositories
- Makes filters work within the theme client so filtering should come for free now
=> Bugfix theme upload

cmd/theme/main.go, commands/watch.go, foreman.go
This allows tools to simply watch for a single file to
change when the workers are completed their tasks instead
of having to wait for something manually or whatever
=> Adds a flag to touch a file when workers go idle

cmd/theme/main.go, commands/configure.go, environments.go
The migrations are kinda dangerous and if it's not in
source control can result in lost settings (ignored files, etc.)
Fixes #53 
Screenshot: 
-----------------------------------
/cc @stevebosworth
=> Adds a confirmation action when migrating a theme

cmd/theme/main.go, commands/common.go, commands/watch.go
This will allow a developer to have various test shops in numerous
configurations and see their changes on all the shops at roughly
the same time.
This feature still needs a bit of work, but it's a good starting point.
- Each shop gets it's own directory watcher, instead we could demux the
channel and feed the results to each of the Formen.
- The output is interleaved so it's difficult to visually tell which shop
got what. Colourized output per shop would be handy
------------------------
Screenshots:
------------------------
Usage:
- `theme watch --allenvs`
----------------------
Caveats:
- This uploads to all shops without prejudice, so you might want to be sure your production shop isn't in that configuration. Maybe we'd want to add an additional argument; something like `--except` …
=> Gives theme watch the ability to upload to all environments

cmd/theme/main.go, commands/configure.go
Not all configurations will include the default "development"
environment. There is a good chance that this is on purpose, and
in that case, the user should just be required to specify which
environment they want to use.
Fixes #62
=> When the default config is missing don't crash

file_watcher.go, file_watcher_test.go, fixtures/layout/theme.liquid, fixtures/templates/customers/account.liquid
The base key for a customer template is more complicated
than regular templates (templates/customer) and these keys
were not being generated correctly. As a result, Shopify
would reject the upload.
This made it impossible to upload customer template changes
automatically
Fixes #60
=> Ensure correct base key for customer templates

install
The instructions for appending to your path causes the entire profile to be overwritten. I wasn't paying attention myself and when I installed it, I took out my entire .zshrc file. Thankfully I have my dotfiles under version control. 
Fixed this to append the path and not overwrite it. I also set it to export the path and not expand the `PATH` variable inside the profile. I just personally find this makes reading my bash/zsh profiles a lot easier.
[![alt](https://screenshot.click/10-00-dj5k2-34zpn.jpg)](https://screenshot.click/10-00-dj5k2-34zpn.jpg)
@csaunders
=> fix installer instructions to append path and not overwrite

asset.go, asset_test.go, fixtures/assets_response_from_shopify.json, fixtures/expected_asset_list_output.json, theme_client.go, theme_client_test.go, utils.go
This is a pretty rough estimation as to which files are
compiled, but most of them typically follow a similar scheme
like "filename.js.liquid" and so on.
There is a chance this might cause some other kinds of bugs though,
so perhaps this isn't the right approach. Another alternative is
to simply detect those files and add them to the ignore section
of the environments configuration.
Fixes #41
Please provide feedback, review, etc. @chrisbutcher
=> Ignores files that are considered to be compiled

commands/replace.go, theme_client.go, theme_client_test.go
Theme replace didn't actually do it's job correctly. It would just replace existing assets on Shopify and get sad if they did not exist. Instead we actually go out and do a correct replacement buy queueing all the remote assets to be destroyed, then replacing any duplicates with update events.
The advantage is somewhat twofold:
- Reduces overall API calls since we only delete assets that don't need to be there
- Is correct
Please review @chrisbutcher 
Fixes https://github.com/Shopify/themekit/issues/64
/cc @stevebosworth
=> Simplifies and fixes replacing a themes assets

asset.go
Files were not being closed after they were used.
Typically this didn't really cause any issues, but sometimes
when working on large projects or when running the application
for an extended period of time the app would crash with a
really undescriptive error message.
The underlying issue was because we were keeping files open.
By defering Close on the file we ensure that we don't exhaust our
File Descriptor limits.
Fixes https://github.com/Shopify/themekit/issues/63
Please review @chrisbutcher 
/cc @stevebosworth
=> Fixes File Descriptor exhaustion

file_watcher.go
Git triggers a lot of these kinds of events that
actually aren't relevant and result in generating
unnecessary events that we don't actually care about
Fixes #56
=> Ignore CHMOD events

cmd/theme/main.go
There were some extra flags showing up that didn't really
make any sense for the user. This fixes that such that
the flag doesn't show up (because it should never really
be used in the first place)
Fixes https://github.com/Shopify/themekit/issues/88
=> Removes --command="download" from theme --help

.env.example, .gitignore, Gemfile, Gemfile.lock, Makefile, release
In order to perform automatic updates we need to know
where the new binary is going to be. While it is possible
to include that in the binary itself, that's fragile.
This is a basic script that builds provides two feeds
along with directories containing the new binary for
each platform.
Clients can either pull down changes from latest.json
or if the version difference is too large apply changes
one at a time (more important if we move over to binary
delta patches).
Right now we'll just upload new uncompressed binaries to
S3 each time and add a new record to the all.json feed.
There is also some guard code in the release script to
ensure that we don't attempt to create an update if
the build hasn't been run or if we've already uploaded
that version.
---------------------
I know that this …
=> Adds Release script to enable automatic updating

cmd/theme/main.go
Fixes https://github.com/Shopify/themekit/issues/89
Though should it perhaps default to `--help` when no arguments were provided instead?
=> Ensure default command

file_watcher.go
Windows uses "\" as a path separator, while Shopify asset paths use "/". This converts the file paths to use "/" so the correct asset path can be generated. Fix for issue at #106
=> Fix file watch issues in Windows

configuration.go, configuration_test.go
Fixes #101. Not sure about the format of the string but at least it
contains arch and os now.
@csaunders
=> Added OS and architecture to user-agent string

Gemfile, Makefile, cmd/theme/setup_darwin.go, cmd/theme/unix_setup.go
Automatically set file limits on startup for unix (non-windows) systems. See #116. 
@csaunders do we have any windows people here that could do a quick smoke test for us?
=> Automatically setting file limits on startup for unix like platforms

configuration.go, configuration_test.go, environments.go, theme_client.go
Configurations now receive some rudimentary checks to ensure they are valid. Missing access tokens or shop domain will now cause an error indicating what environment failed and what key is missing. 
Fixes #119  (hopefully)
@chrisbutcher
=> LoadConfiguration now returns errors when the config is missing values

commands/replace.go, commands/replace_test.go, theme_client.go, theme_client_test.go
Found that the glob used in `ThemeClient.LocalAssets()` was not actually matching any subdirectories. Replaced the glob with a file walker. This shouldn't break anything, but still, it'll change the amount of files watched. 
Could anyone :tophat: ? 
Fixes #102. 
@chrisbutcher @cshold
=> Using file walk instead of glob to find files in local assets

cmd/theme/main.go, commands/bootstrap.go, theme/asset_test.go
io.WriteString() is more optimized for cases when the argument given is already evaluated as a string. This PR uses it any place we'd otherwise do `Write([]byte(fmt.Sprintf("Foo %s", "bar"))) etc`. Cleaner and faster!
+ Lint-based style changes
@ilikeorangutans for review
=> Using WriteString instead of Write([]byte)

event_filter.go, event_filter_test.go
Fixes #140
Passing an empty string to the glob function crashed themekit. Added
simple check. Need to figure out why we even handled an empty string at
that point.
@chrisbutcher @stevebosworth
=> Fixes a strange crash

cmd/theme/main.go, commands/configure.go, configuration.go, configuration_test.go, version.go
Part of https://github.com/Shopify/themekit/issues/104
* Adds `password` to Configure command workflow, which holds the same value sent to Shopify under the header `X-Shopify-Access-Token`.
* The logic which allows either to be used interchangeably is [here](https://github.com/Shopify/themekit/pull/145/files#diff-bee1b19602a9f84a06f44e111f79a479R93).
* The naming of this header is a source of confusion. In the previous themes gem, and in previous incarnations of `config.yml`, the term `password` is used. It's also used within the Shopify Private Apps UI, as seen in the related issue above.
* This PR adds support for `password` as the preferred flag name, and `config.yml` key. Eventually we should deprecate the term `access_token` themekit (a warning is added when calling `theme configure` …
=> Support 'password' in config, interchangeable with access_token

cmd/theme/main.go, commands/args.go, commands/configure.go, configuration.go, configuration_test.go, environments_test.go, theme_client.go
Fixes https://github.com/Shopify/themekit/issues/157
* Parse theme_id in config.yml as an integer, to ensure it's valid (at least numerical)
* Enforce required values in `theme configure` (TODO update docs)
* domain
* password
* theme_id (now required)
=> Handle blank or non-integer theme_id specified in config.yml

dev.yml
I received `failed to activate ruby 2.2.3. you may need to run dev up.` when trying to run `make install` after running `dev up`.
=> Adds ruby to dev up for easy setup

commands/args.go
I found that I could not use `theme configure` because the `theme_id` argument was not passed along and it was required. So I added this into the default config options so that it is passed along to the config command.
=> Adding in theme id to the default config args

commands/download.go
Fixes https://github.com/Shopify/themekit/issues/165
Resolves by checking if the file download is a JSON asset and pretty writes. If the file is not JSON, write as normal.
@tanema @chrisbutcher
=> Pretty write JSON downloads

cmd/theme/main.go, kit/configuration.go, kit/environments.go
fixes https://github.com/Shopify/themekit/issues/175
Just changed the validation of configurations to only happen when they are fetched using `GetConfiguration` rather than when all of the environments are unmarshaled.
=> Validate Environment only when required

commands/watch.go, kit/file_watcher.go, kit/theme_client.go
fixes https://github.com/Shopify/themekit/issues/159
I made sure that watch now removes files but also touched up the file watcher code to ensure that it will accurately respond to all events that it gets.
cc @chrisbutcher @jessicaxiejw @ilikeorangutans
=> Supporting remove event in watch.

Makefile
According to this: https://github.com/upx/upx/issues/4 we cannot use upx anymore. This is okay because I haven't tested it on window either and some windows virus programs can block packed binaries as well. So probably for the best.
cc @ilikeorangutans @chrisbutcher
=> UPX breaks binaries for Sierra

kit/file_watcher.go
v0.4.4 was release with bad file watching debouncing. This will fix that. This was my fault. I tried to be overzealous with refactoring it so that the timeout didn't run constantly and then have a low timeout for better responce. My logic was faulty so I have reverted it and made the timeout higher to filter events better.
cc @chrisbutcher @ilikeorangutans 
ref https://github.com/Shopify/themekit/issues/220
=> Took out bad debounce logic

kit/file_watcher.go
fixes https://github.com/Shopify/themekit/issues/223
I made the timeout larger and took out chmod events because they were causing double events.
=> fixing double events and fine tuing timeout amount

commands/download.go
To make downloads more dependable I have taken out the concurrency since it doesn't really speed it up and only makes download less deterministic. I also added more error logging so I can find errors when they happen.
This may fix https://github.com/Shopify/themekit/issues/221
=> More dependable downloads

kit/http_client.go, kit/shopify_response.go, kit/shopify_response_test.go
fixes #246 
lIn asset events, after the request is finished theme kit would set some values on the response to generate better errors, however if the request never completed successfully then the response would not exists and the program would panic. I added catching for that so that the error will be logged and the application will not panic.
=> Fixing bad request handling

kit/file_watcher.go, kit/file_watcher_test.go
fixes https://github.com/Shopify/themekit/issues/233
There were still problems with the file updating debouncing. I had more of an event loop pattern for my debouncing where it would check all events every second. Now I have moved toward a per event timeout which means each event will be handled one second after the last event on a file was seen. The last seen event will be handled. If this is more of a problem in the future we can provide configuration for the debounce value.
@chrisbutcher
=> Changing debounce from single timeout to a timeout for each event.

scripts/install
Current install script uses print statements without parentheses, which causes errors in Python 3...
```
$ python3 install
File "install", line 75
print "Downloading themekit from %s/%s" % (self.host, self.path)
^
SyntaxError: invalid syntax
```
For this new version of install, I used 2to3 to fix the print statements and a few other minor issues. It works with 2.7, 3.4 and probably any Python version in between. 
This does NOT work with 3.5 because of some breaking module name changes with httplib and urlparse.
=> Make install script work with Python 3

docs/_config.yml, kit/errors.go, kit/file_watcher.go, kit/http_client.go, kit/shopify_response.go, kit/shopify_response_test.go, kit/version.go
fixes #249 
There was an issue where update events had many ops in the the `event.Op` field so when the event was interpreted the event type was missed and the default event `Create` was set. This caused a 404. 
Also I had noticed that some errors mentioned by @chryton had very poor error reporting. This has also been fixed.
=> Fixing create errors and bad error messages.

cmd/configure.go, cmd/theme.go, kit/configuration.go, kit/configuration_test.go, kit/environments.go, kit/http_client.go, kit/http_client_test.go, kit/theme_client.go, kit/theme_client_test.go
fixes https://github.com/Shopify/themekit/issues/248
The configuration is now accessed as a pointer rather than value so when it is changed in one place, all other references to the same config will have those changes. It probably should have been a pointer before anyways since it is the most passed around object.
@chrisbutcher
=> Changed how configuration is used

kit/configuration.go, kit/http_client.go
There was an issue recently #262 where the user had specified `http://` before thier store domain and since I allowed http urls for testing, it was a valid config. This resulted in shopify responding with 403 because ssl is required. So to allow testing to stay easy but also default to ssl for normal use cases I have just added better prefix checking on the domain. 
@chrisbutcher
=> Made more strict checking for test domains

kit/event_filter.go, kit/file_watcher.go, kit/file_watcher_test.go
fixes #251
Also mitigates #253
Some users are having some problems with OSX's low file descriptor limit. I cannot just simply make the file watcher only watch valid files and not the directories because that will drop created events. I believe that by ignoring the root directory we will miss a lot of application/VCS/processor data. The main side effect of this may be that if the user creates a new folder (sections for instance) it will not get picked up.
@chrisbutcher Any thoughts on if this will effect anything else?
=> Adding more file ignores and ignoring the main directory from watcher

kit/file_watcher.go, kit/file_watcher_test.go, kit/theme_client.go
fixes #267 
In the last refactor, the notify file functionality was accidentally removed. This PR adds it back in. It will touch the file, update the file's access and modify times whenever there are no fs events in the queue after one second.
@chrisbutcher
=> Adding back in the notify file functionality

fixtures/project/valid_config.yml, kit/configuration.go, kit/environments.go
fixes #268 
The directory config in the config file was not properly respected. This adds in support for that config as well as filtering out default values from marshalling into new config.yml files.
@chrisbutcher
=> Allowing directory config to come from the config file

cmd/download.go, cmd/theme.go, cmd/theme/setup_darwin.go, kit/http_client.go, kit/logging.go, kit/version.go
fixes #273 
The log now looks like this
I also took out all the extra logging functions so that it is clear where messages are logged, either sdtout or stderr.
@chrisbutcher
=> Logging work

kit/event_filter.go, kit/event_filter_test.go, kit/theme_client.go, kit/theme_client_test.go
We were doing sorting, filtering compiled assets and  filtering ignored files in a couple places so I put all these operation into the filtering code. It has the side effect of doing less looping so slightly more performant, but mostly better code.
@chrisbutcher
=> Small refactor to dry up filtering code

kit/errors.go
fixes #288 
Connection issues were not being output from the download command because they were not considered fatal. This is because the status code was 0 and so it was not in the fatal range. I have changed the range of fatal code to catch < 200 status codes.
@chrisbutcher
=> Catching less than ideal list errors

kit/file_filter.go, kit/file_filter_test.go, kit/file_watcher.go, kit/file_watcher_test.go, kit/theme_client.go
fixes #287 
First off I renamed `eventFilter` to `fileFilter` since it is used to filter filenames and not just the file watcher events.
Secondly the main problem is that we were filtering out compiled files by filename and not by extension. So it was filtered by thinking that the file path `app.js.liquid` contained the path `app.js` so that means `app.js` is compiled. However this is a problem when one of our users wanted to use source maps so when they had a `theme.css` and a `theme.css.map`, themekit incorrectly assumed that `theme.css` was compiled. So I changed the strategy so the instead themekit checks for the file by checking the list for `app.js`+`.liquid`. This make filtering compiled assets simpler and faster.
@Thibaut @chrisbutcher
=> Better file filtering

kit/asset.go, kit/asset_test.go, kit/file_watcher.go
fixes #295 
fixes #296 
There is an issue where `templates/customers` is not being watched on windows. This PR will fix this issue and hopefully support paths in a more uniform way.
This is still WIP just because I need to test on a VM still and I don't have the time right now.
@chrisbutcher
=> Fixing Windows Watch Paths

kit/file_filter.go, kit/file_filter_test.go, kit/file_watcher.go, kit/file_watcher_test.go, kit/theme_client_test.go
fixes #300 
Filtering out files that are not in the project workspace for all actions. This will minimize all the 404 responses from file not being in the project workspace. It will also minimize requests to Shopify which will make upload and replace faster since there are no wasted connections.
@chrisbutcher @stevebosworth
=> Restrict all operations to project files and non filtered files only.

cmd/download_test.go, cmd/remove.go, cmd/remove_test.go, cmd/replace.go, cmd/replace_test.go, cmd/theme.go, cmd/upload.go, cmd/upload_test.go, cmd/watch.go, cmd/watch_test.go, docs/configuration/index.md, kit/configuration.go, kit/http_client.go
fixes #303
This allows users to use the `allenvs` flag and protect their live config.
@chrisbutcher
=> Readonly flag

fixtures/project/assets/application.js, kit/asset.go, kit/asset_test.go, kit/environments_test.go, kit/file_filter.go, kit/file_filter_test.go, kit/file_watcher.go, kit/file_watcher_test.go, kit/path.go, kit/path_test.go, kit/theme_client.go
fixes #308
fixes #307 
fixes #305 
I finally bit the bullet and just isolated path functions so that they can be maintained in a separate environment and not be effected by other changes. All the path handling is in one spot within helpers that can be used outside of there so that the path manipulation doesn't change. Also since the file filtering now filters files to be strictly inside the project, this cleared up the amount of spots that paths are checked
@chrisbutcher
=> Fixing windows path handling in 0.6.2

docs/configuration/index.md
`--directory` is not a valid flag, however `--dir` is. Updated docs to match.
=> Update docs to correct directory flag

cmd/upload.go, cmd/watch.go, cmd/watch_test.go, kit/asset.go, kit/file_watcher.go, kit/file_watcher_test.go, kit/theme_client_test.go
fixes #312 
The asset loading became more strict in the last version but did not account for file removal in watching. This PR fixes that. Also since the watcher no longer returns any errors the callback interface was simplified.
@chrisbutcher @ilikeorangutans
=> Fixing remove event in file watcher

cmd/download.go, cmd/download_test.go, kit/asset.go, kit/asset_test.go, kit/http_client.go, kit/http_client_test.go, kit/theme_client.go, kit/theme_client_test.go
fixes #318 
ThemeKit was using an API endpoint incorrectly so asset listing had to be changed to take out the attachment and value data from the list queries. (https://github.com/Shopify/shopify/issues/98379)
This will make download and replace a lot more dependable for larger themes however it does *feel* slower to download. It will however make replace much faster.
@chrisbutcher 
cc @NathanPJF @DrewMartin @nicday @Thibaut Just to let you know that I have managed a fix for this issue.
=> Took out values and attachments from asset list queries

cmd/theme.go
Just something I ran into while `grep`ping the `theme --help` output for `environment` 😹
=> Fix typo in theme.go

scripts/install
Fix for https://github.com/Shopify/themekit/commit/9ae31714bc1a96af2f5703049538a45f989b983d#commitcomment-20733658
"0755 is not a valid numerical literal in python 3.5. If you change it to 0o755, it will be compatible with both 2.7 and 3.5. See: https://www.python.org/dev/peps/pep-3127"
=> python 3 fix

cmd/download.go, cmd/download_test.go, cmd/upload.go, cmd/upload_test.go, kit/asset.go, kit/asset_test.go, kit/theme_client.go, kit/theme_client_test.go
fixes #264 
fixes #310 
This adds the functionality to upload directories by calling `theme upload ./assets` or `theme upload assets` This will upload all the files recursively in the the directory. It also enables the user to download using wildcards like this: `theme download assets/*.js`
=> Upload directories and download wildcards

cmd/remove_test.go, cmd/watch.go, cmd/watch_test.go, glide.lock, glide.yaml, kit/file_watcher.go, kit/file_watcher_test.go
fixes https://github.com/Shopify/themekit/issues/236
This will keep watch on the config file as a priority over any other file so that when it changes, all other events are stopped and watchers are reloaded.
=> Reload Watch on Config Change

cmd/bootstrap.go, cmd/bootstrap_test.go, cmd/download.go, cmd/open.go, cmd/remove.go, cmd/replace.go, cmd/theme.go, cmd/upload.go, glide.lock, glide.yaml
The aim of this PR is to simplify output for download, replace, and upload. It also has the nice addition of being able to show progress. I am going to leave this PR up for a while because I am not sure if anyone wants this. I just did it while on the train to summit.
*note:* This does not change the output of watch.
**Without verbose**
**With verbose flag**
@NathanPJF  would this conflict with slate's usage?
=> Verbose flag & Progress Bar

cmd/download.go, cmd/remove.go, cmd/replace.go, cmd/upload.go
fixes #333 
The file counts were inaccurate. The count was having one taken away incorrectly. This PR makes better file counts.
The reason this happened is that file uploads and downloads were changed in a different PR outside of the progress bar work so it's work conflicted with this.
=> Fixed file counts for single file uploads

fixtures/symlink_project, kit/file_watcher.go, kit/file_watcher_test.go
fixes #336 
There was a problem with walking a directory that is a symlink. This resolves the symlink so that the directory can be walked correctly.
=> Adding handling in case the root directory is a symlink

CONTRIBUTORS.md, Makefile, circle.yml, docs/index.md, scripts/EnvVarUpdate.nsh, scripts/release, scripts/themekitInstaller32.nsi, scripts/themekitInstaller64.nsi
fixes #146 I think once there is a proper windows installation all platforms will be covered. There is no reason to make a Debian package for a single binary package.
This adds windows installer functionality so that windows users don't have to edit environment variables. This will automatically put the binary into the `C:\Program Files\themekit` directory then put that directory into the users PATH variable. It is also now streamlined into the distribution workflow so that the user just needs to have `makensis` installed and they don't need to know how to build the windows installer.
=> Added windows installer to the docs and NSIS install script

cmd/theme.go, kit/environments.go
fixes #345 
- Added better error messages for config loading 
- Also json was the first file type to be loaded and since it isn't recommended it was put to the end of the loading order.
=> Config loading fixes

kit/logging.go
Currently color support causes output to the windows command line to seem a bit jumbled because cmd.exe doesn't know how to interpret the color codes. This fixes that so that windows developers will see the color and have properly formatted output.
=> Adding windows color support for logging to the console

README.md, circle.yml, kit/asset.go, kit/asset_test.go, kit/file_filter.go, kit/release.go, kit/release_test.go, kit/theme_client_test.go
Go 1.8 introduced a new sorting mechanic so that I could take out a lot of sorting code. It really cleans stuff up.
=> Taking out all the extra sorting code fort sort.Slice in go1.8

kit/event_map.go, kit/event_map_test.go, kit/file_watcher.go, kit/file_watcher_test.go
fixes #349 
After I refactored the watching event loop so that I could more accurately profile the cpu usage actually went down to peak 7%. This could be because I have moved a large amount of variables from anonymous functions into the watcher struct. This could the GC less like to take longer in figuring out if the variables are needed or not. This is only a guess because I am still not quite able to figure out what was causing the performance issues.
=> Refactoring watch for performance

cmd/watch.go, kit/file_watcher.go
fixes #361 
I have finally bit the bullet and added minimal vcs integration to help developers when they change branches. I have only supported git and mercurial since they have more common branch like usage. We may be able to add more in the future. This for now only works if the config file is in the root of the repo since the repo watching is relative to the config file.
=> Added minimal vcs integration for branch changing

kit/http_client.go, kit/http_client_test.go, kit/theme_client_test.go
There was a problem query params when there were spaces in the file names. This now encodes the params properly.
=> Fixing query params encode so that it wont break with weird file names

cmd/theme.go, docs/commands/index.md
fixes #374 
Sometimes devs may want to upload changes to thier ignores or download them only once so I added a flag that will short-circuit the ignore configs. I made it purposefully long so that it cannot be done by accident.
=> Adding a breaker for ignores

cmd/open.go
fixes #381 
Since the documented behaviour specifies that it prints out the url that is being opened, the message is no longer suppressed with the verbose flag.
=> Disable verbose flag on open

kit/file_watcher.go, kit/file_watcher_test.go
fixes https://github.com/Shopify/themekit/issues/392
**Problem**
In Atom and Sublime Text when deleting a file instead of a delete event, a rename happens. The editors rename the file to be in the trash can. Also while testing this it seems that the same would happen when renaming a file. The renamed file would have no content with the original filename and stay existing with the newly named file
**Solution**
*Change rename events to delete files.*
This solves renaming because it will delete the first file then create a new file with the new name and content.
**Problems**
This may cause confusion if a new developer tried deleting or renaming critical files because it will fire a delete action on the critical file and fail. Then it will succeed in creating the new file. Unfortunately I …
=> Handling renaming events better

kit/theme_client.go, kit/theme_client_test.go
fixes https://github.com/Shopify/themekit/issues/279
This will automatically DELETE the liquid file and then re-upload the non-liquid file. Currently it shows no warning and the only indication that any different happened is that it takes a fraction of a second longer to finish the update.
TODO
This and the other open PR (https://github.com/Shopify/themekit/pull/395) should really fix up any file confusions for renaming and compiled files.
cc @NathanPJF for slate
=> Fixing updating compiled assets

docs/index.md, scripts/install
fixes: https://github.com/Shopify/themekit/issues/401
I made the naive assumption that `/usr/local/bin` would always exist however on a fresh install of OSX this is not the case. For most cases, this path has been created by other software installations and so it has not been an issue. This PR adds checking and creation of the install directory before creating the theme binary.
=> Adding condition to ensure that install path exists

cmd/open.go, cmd/open_test.go
Fixes https://github.com/Shopify/themekit/issues/405
This added the ability to open a preview for a live theme. I also added a warning when this is the case because technically the preview is the live shop so the developer should be aware that they are editing a live theme.
I also cannot open the editor like this because I require a theme id to open the editor so I output an error message for this case.
=> Added handling for opening live themes as well as tests for open

scripts/install
fixes https://github.com/Shopify/themekit/issues/410
One user was having an issue with installing on `darwin i386` which is a weird arch for OSX but I added it anyways. I also added handling incase this happens in the future so that it will fail gracefully and the user will know what to do.
=> Better unknow arch handling for install.

cmd/bootstrap_test.go, kit/asset.go, kit/asset_test.go, kit/file_filter.go, kit/file_filter_test.go, kit/file_watcher.go, kit/file_watcher_test.go, kit/path.go, kit/path_test.go, kit/theme_client.go
fixes https://github.com/Shopify/themekit/issues/388
It was noticed that some paths would match up with paths in the node_modules folder causing weird errors while uploading. This exposed the fact that path matching was too fuzy and probably eating up extra cpu just checking large node modules structures. 
This PR restricts all path matching, any function that makes sure a file is valid for upload is restricted to the root directory as specified by the users configuration. It was also exposed that file filtering probably didn't work through symlinks either so that was fixed in this PR as well.
This is still WIP because it is quite a substantial change and could have some potential for bugs so I will need to test it thoroughly. The tests were not changed much and they all pass however I …
=> Restricting the path checking to be more strict about project paths only

cmd/configure.go, cmd/configure_test.go, cmd/theme.go, cmd/theme_test.go
fixes #417 
- Added wildcards to environment variables however depending on your shell you will probably need quotation marks around any wildcards like: `theme --env="client-*" uplodate`
- Added the ability to use multiple env flags like: `theme --env=production --env=development upload`
To implement having several *selected* environments/clients loaded at one time I had to implement having the ability to load independent environments. This added the ability for multiple env flags which I think is a good feature to have as well.
Changed how environments/theme clients are loaded to have a environment name matcher. 
Tests have been added for all situation for loading environment. This seems low risk
=> Added the ability to glob env flag and have multiple env flags

cmd/bootstrap_test.go, cmd/command_arbiter.go, kit/configuration.go, kit/configuration_test.go, kit/environments.go, kit/environments_test.go
In the newest version since all environments are loaded simultaneously to check asset versions there is some problems about which environments that flags and environment variables take effect. I thought about this for a long time and decided that it is much more intuitive to only apply them to the active environments. This means that they are applied to the environments that the developer expects to be working on and not any of the other environments. This PR makes it so that these configurations are only merged in when the environment is active.
=> Flags and Envs only take effect on active environments.

cmd/command_arbiter_test.go, cmd/file_manifest.go, cmd/file_manifest_test.go, kittest/config.go
While testing I noticed that if I
- downloaded a theme
- added a new environment to my config.yml
- ran `theme download` again
All files would be skipped because they had not been updated and so the new environment versions were not added to the `theme.lock`. This PR adds in functionality that will add missing versions to the theme.lock when the manifest if built. This means upon running any command, themekit will check each client, and add any missing versions to the manifest.
=> Added backfilling for versions not yet recorded when manifest is built

cmd/open.go, cmd/theme.go
fixes #427 
This will enable the user to open the preview in a target browser by name. This name is defined by the OS so I cannot make simplified options like `--canary` This means that 
- `theme open -b=firefox`
- `theme open --browser="google chrome"`
- `theme open -b="google chrome canary"`
Will all work if those browsers are installed on the system however `theme open -b=canary` will not work. I currently have no way of querying which browsers exist so I cannot create the simplified options or allow fuzzy matching of browser names.
=> Added a browser flag for opening editor in different editor

cmd/file_manifest.go, cmd/file_manifest_test.go
Since fetchable files were generated from the manifest and remote files are coming from all sources, if another environment didn't ignore the file then it would still exist in the remote manifest. This will check that the file is in the current environment before adding it to the fetchable list.
=> Download was not ignoring files properly on download

cmd/command_arbiter.go
rel #436 
This PR doesn't narrow down the reason it happens but it will prevent themekit from ever hanging like this. If the count is equal to 0 it will not start a progress bar.
=> Saftey check for progress bar

cmd/file_manifest.go
While doing QA I realized that once a file is in the manifest and the timestamp is updated, the file will no longer be downloaded if the file is deleted. 
Previously while pruning files from the manifest I would only prune a file if it didn't exist on remote as well as on disk however I have changed it to prune files that only don't exist on the disk. This is better because it doesn't matter if the file is still on the remote. The user cannot update/overwrite file changes if the file does not exist. Now that the file will be pruned from the manifest if it didn't exist, this means it will be downloaded when download is called since it no longer exists in the manifest.
=> Prune now only prunes files not on disk

cmd/file_manifest.go, cmd/file_manifest_test.go, cmd/remove_test.go
When running the remove command, it would not remove a file that was not updated but because it was checking that the remote time was Before local and if they were equal it would assume that the file had been modified.
=> Remove was not removing files with the same date

docs/faq/index.md
fixes #316 
Instead of re-inventing the wheel and re-implementing yet another browser reload tool and then have to deal with requests for asset compilation features, I thought that it was better to add documentation that point to other tools that are already dependable for these features. This also has the bonus of the other tools having features that different users require.
@chrisbutcher for grammar help :D
=> Added some live reload documentation in the FAQ

cmd/bootstrap.go
fixes #444 
When I refactored everything I made the incorrect assumption that the config command was only used for the development environment. This adds back in the `env` flag behaviour.
=> Fixing env flag on config command

cmd/command_arbiter.go, cmd/command_arbiter_test.go
fixes #446
Currently themekit checks all environments strictly for version checking however this does not allow for reusable config like this:
```
production: # LIVE WEBSITE
theme_id: ********
readonly: true # safety switch; toggle to deploy
<< : *common
config: &common
password: *********************
store: storename.myshopify.com
ignore_files:
- src/
- node_modules/
- Gulpfile.js
- package.json
```
Because the `config` environment would be invalid. I don't love this because if some of the environments are invalid I won't be able to backfill the manifest with versions. However when upload/replacing on different environments, the backfills aren't *really* necessary. I was just being greedy with that information.
=> Skipping invalid environments in the manifest, allowing reusable config

cmd/command_arbiter_test.go, cmd/watch_test.go, kit/configuration.go, kit/configuration_test.go, kit/file_watcher.go, kit/file_watcher_test.go
fixes #447 possibly related to #454 
This will move symlink eval to config validation so that the whole codebase deals with one valid directory path.
=> Added symlink eval to config validation

cmd/theme_diff.go, cmd/theme_diff_test.go
rel: #456 
The diff message can be confusing and causes some users to be unaware that running `theme download` would overwrite their local changes. I am hoping to clarify any issues with this by re-writing this message.
@chrisbutcher @t-kelly Maybe you two can give me feedback on good verbiage for this?
=> Clarifying diff message

cmd/bootstrap_test.go, cmd/command_arbiter.go, cmd/command_arbiter_test.go, cmd/file_manifest.go, cmd/file_manifest_test.go, cmd/theme.go, kit/configuration.go, kit/configuration_test.go, kit/environments.go, kit/environments_test.go, kit/file_watcher_test.go, kit/version.go
fixes #459, #461, #462
possibly related: https://github.com/Shopify/themekit/issues/460
When this was first designed, I made the assumption that the developer would develop on one branch and then upload others. When they did so I would compare timestamps from development to deploy. This is incorrect. The timestamps should only ever be set in the manifest when a change has been made specifically on that file in that environment because that is the only time we are certain that we have captured the state accurately.
As such themekit no longer loads all environments, and so this will fix the issue with the environment variables and all the issues with shared configuration. This also just simplifies how themekit interacts with the config and makes it more predictable.
=> Changing how the manifest deals with diff dates

cmd/file_manifest.go, cmd/file_manifest_test.go, cmd/ystore/ystore.go, kittest/config.go
fixes #466 
In the previous version, the functionality to load all valid environments was taken out however the manifest pruning that checked the environments was not removed. This PR removes that extra pruning that is no longer needed
=> Fixing over zelous manifest pruning

cmd/command_arbiter.go
Currently, if the config is invalid the output will just inform the user that no valid configurations could be loaded. This PR will fix that and tell the user exactly how  the configuration is invalid.
=> Fixing config validation output

scripts/install.ps1
Use try-catch to exit PowerShell script on error condition (abnormal circumstances).
Script should not continue and report "Install Complete" when there is an error. Instead, it should print out an error message and exit with an exit code indicating failure.
Note that `Write-Output` writes to the pipeline while `Write-Host` writes to the host terminal (usually the user's screen). Only `Write-Host` provides coloring options. _(We should be using `Write-Host` for all messages, but I didn't change that here. I can open another PR for that.)_
_(I'm not sure of the relevancy of some of the checklist items, as I'm changing the PowerShell script only. Please let me know if you need more info.)_
Mentions: @tanema, @chrisbutcher
=> Use try-catch to exit PowerShell script on error

scripts/install
fixes #508 
It isn't immediately clear that python2 is required for the installation script. This adds a check for the python version so that the error can be more appropriate.
=> Making python2 requirment clear at installation

src/cmdutil/util_test.go, src/env/conf.go, src/env/conf_test.go
fixes #545 
Themekit was validating all environments on deploy and we really should only be validating the environments that are requested. This takes out validation of a whole configuration file and only validates when an environment is fetched.
=> Dont validate all envs on load

cmd/deploy.go, cmd/deploy_test.go, src/shopify/asset.go, src/shopify/asset_test.go
fixes #548 
When loading files from directories,  the filepaths were not correctly loaded and normalized on windows. This will normalize the paths
=> Checking windows paths during deploy

scripts/install, scripts/install.ps1
fixes #541
As I closed this issue I realized the install scripts do not check the binary digests so I added this to both of the install scripts.
=> Adding checksum checks to install scripts

src/cmdutil/util.go
fixes #564 
Themekit was clearing ignore but note before creating a theme client so the themeclient still had all of the ignore.
=> Fixing disable ignores

cmd/deploy.go, cmd/new.go, src/file/watcher.go
fixes #553 
There was a bug in fsnotify that didn't allow me to shutdown the watchers inline to avoid deadlocks. Since the bug was fixed, I can ensure that watching stops before ending the command.
=> Shutdown watching appropriately

cmd/configure.go, cmd/deploy.go, cmd/download.go, cmd/get.go, cmd/new.go, cmd/open.go, cmd/remove.go, cmd/remove_test.go, cmd/watch.go, src/cmdutil/util.go, src/cmdutil/util_test.go
This allows the context to hold state across operations. This was blocking error reporting refactoring.
=> Handle CTX with a pointer

cmd/publish.go, cmd/publish_test.go, cmd/theme.go, src/cmdutil/_mocks/ShopifyClient.go, src/cmdutil/interfaces.go, src/shopify/theme_client.go, src/shopify/theme_client_test.go
Rel: #583 
This adds a publish command to themekit so that a developer can publish a theme without opening admin.
It can be used by running 
```
> theme publish --env=production
```
=> Adding a publish command to themekit

changelog.txt, cmd/theme.go, go.mod, go.sum, src/cmdutil/util.go, src/env/_testdata/projectdir/valid_config.yml, src/env/conf.go, src/env/conf_test.go
This PR encapsulates 2 main features.
- Automatically load environment variables from a file during runtime
- Allow environment variable interpolation in the config 
This will allow developers to much more easily commit their code to public repos without revealing their passwords or their clients.
The normal user configuration paths are used so depending on OS the path used would be:
Windows:  `%APPDATA%\Shopify\Themekit\variables` 
Linux/BSDs: `${XDG_CONFIG_HOME}/Shopify/Themekit/variables` 
MacOSX: `${HOME}/Library/Application Support/Shopify/Themekit/variables`
Themekit will also look for a variables file within the project directory. There has also been a flag added `--vars` will provide a path to a variables file.
The format of these files would look like a normal .env file:
``` …
```
=> Add automatic environment variable loading and Variables in yml config.

changelog.txt, cmd/watch.go, go.mod, go.sum, src/file/watcher.go, src/file/watcher_test.go
fixes #519 
fsnotify is beginning to collect a lot of tech debt and it has been unreliable to be consistent across operating systems.
It currently is broken on windows 10 because windows sends events even when a file is viewed. The new backend that I have added uses pollling across all systems, and while not as ideal, it uses checksums and timestamps to check changes and smooth out events. 
Also I have not seen any cpu usage spike after switching. It still hovers around 0.4%
=> Changing the file watcher backend

changelog.txt, cmd/deploy.go, cmd/deploy_test.go
fixes #595 
In issue 595, the developer was confused when he had a file names [filename].js and filename.js.liquid but expected them both to be uploaded to shopify.
The deploy command will now throw and error and halt execution if a developer tries to deploy a theme with conflicting files in it. This will half them and demand that they fix this before they continue. This does not cover all cases as the watch command is still capable of causing this confusion but less likely to become a complete blocker while using watch. I also do not want to add the addtional overhead of either keeping track of existing files to check for conflicting files, or hitting the FS every time the developer makes a change.
=> Adding an error that will stop developers from uploading compiled assets

src/env/conf_test.go, src/env/env.go, src/env/env_test.go, src/file/watcher.go, src/file/watcher_test.go
fixes #600 #599 
This has two fixes in it.
- Fix the directory config for watching a subdirectory
- Add a minimal amount of debouncing back into the new filewatcher.
The debouncing just simply drains the event channel after the poll interval happens and then deduplicates them.
=> fix directory config and debounce watcher events.

src/release/release.go, src/release/release_test.go
fixes #604 
There is an issue where if the user tries to update to a version that is invalid semver, themekit will panic. This adds a check before the use of any user-inputted version so that the rest of the release package can use it with confidence.
Sorry @batasrki I was already getting some themekit work done, so I did this really quick as well.
=> Added a check for a valid version before all version uses

docs/index.md
Changed the path from `;C:\Program Files\Theme Kit` to `C:\Program Files\Theme Kit`
=> fixed typo in Windows Installation path

.github/CONTRIBUTING.md, Makefile, src/file/watcher_test.go
Related: #544 
This is in hopes of fixing the certificate issues, thanks to @Aeon investigation. This simply disables cgo while building themekit and adding tests for that situation.
This PR also has some fixes to try and mitigate a flaky test.
=> Disabling cgo to fix certificate issues

cmd/download.go, cmd/download_test.go, src/env/env.go
related #631 
This just adds asset names to the error responses in download so that it is clear which files are raising errors.
=> Better download errors

go.mod, go.sum, src/file/watcher.go, src/file/watcher_test.go
Fixes #608 
This PR changes from watching directories specifically to watching the root directory recursively and uses a filter hook to split concerns of events and filtering.
This will allow picking up files in new folders and makes our code a bit easier to test and understand.
=> Making the file watcher more flexible

theme-template/layout/theme.liquid
fixes #652 
There was a missing html opening tag in the layout when generated. This fixes that.
=> Adding a missing html tag

docs/configuration/index.md
fixes #646
Adding documentation in the docs site for the configuration flag. It is good to keep in mind that not all people using themekit are using it through the command line so we cannot entirely depend upon the command line output as documentation.
=> Document the config flag

theme-template/assets/application.scss, theme-template/assets/application.scss.liquid
Creating a new theme recently, I found that the default `application.scss` file wasn't compiling, leaving me with a 404 error for what should have been the theme CSS file.
Some searching led to [this post](https://community.shopify.com/c/Shopify-Design/Scss-file-doesn-t-compile/m-p/464829/highlight/true#M120822) and on to [this blog post](https://www.shopify.com/partners/blog/a-beginners-guide-to-sass-with-shopify-part-3) that suggested the scss file needed a missing `.liquid` extension.
I changed the file to `application.scss.liquid` and it worked!
This PR proposes changing the file to be `application.scss.liquid` by default, and adds comments to flag that SASS gets compiled on deploy, and that `@import` isn't supported.
=> Change application.scss to application.scss.liquid

docs/scripts/install.py
This allows the installer script to run under either Python 2 or 3, at the user's discretion, or with whatever happens to be installed on the system as the default version. As time goes by, Python 3 will be more commonly the default, and even the only, Python version pre-installed on most systems.
Additionally, it is now also possible to pass the desired install path as an argument when running the script, as the path was already accepted in the installer class, but not able to be passed to it without modifying the installer. Example: `./install.py <path/to/where/i/want/themekit/installed>` Of note, the default install path has not changed and will apply if the user doesn't specify one.
/cc @tanema
=> Py3+ compatibility for install script

docs/faq/index.md
**LivePage Chrome Plugin** doesn not exist anymore in the Chrome Web Store. It now needs to be built from the source code as [the website says](https://livepage.mikerogers.io/).
> As of the 10th of February 2020 is not actively maintained. You can still find the source code on GitHub if you'd like to use it.
=> Fix broken link

.gitignore
When running the test command from `.travis.yml` locally, this file is left behind.
=> Ignore coverage.txt

cmd/deploy_test.go, cmd/download.go, cmd/watch_test.go, src/shopify/_testdata/project/assets/app.json, src/shopify/_testdata/project/assets/app_alternate.json, src/shopify/_testdata/project/assets/template.liquid, src/shopify/asset.go, src/shopify/asset_test.go
Pairing with @ayronshopify
We've updated the Asset model to have a `Checksum` field so that we can process checksums in the future and calculate/compare them to the checksums from the Asset REST API.
We've added new tests for the Asset model to look at the various filetypes that we may encounter (`.liquid`, `.json`, `.js`). 
We've also added logging in the verbose (`-v`) mode for downloading which allows us to see the checksum for each file (as retrieved from the API). We think this will be useful for debugging or comparing checksums locally.
=> Add checksum to Asset model

cmd/deploy.go, cmd/deploy_test.go, cmd/download.go, cmd/download_test.go, src/shopify/asset.go, src/shopify/asset_test.go, src/shopify/theme_client.go, src/shopify/theme_client_test.go
* Refactored to pass around Assets rather than files paths. This is to make it easier to compare checksums.
* Implemented behaviour to skip downloads where the local checksum matches the server checksum.
* Added some verbose output for easier troubleshooting to indicate skipped files.
* Updated the tests as necessary.
* Fixed an existing bug in the `compileAssetFilenames` method.
* Altered the API call to fetch checksum from server.
Pairing with @tanema, @ayronshopify and @carmelal
=> Skip download of files if checksums match

cmd/deploy.go, cmd/deploy_test.go, cmd/download.go, cmd/watch.go, src/file/watcher.go
Co-authored with @ayronshopify 
Depends on this Core change: https://github.com/Shopify/shopify/pull/251785
TODO:
This PR adds behaviour so that if a files local checksum matches the remote checksum, then we skip it.
The existing upload process had two variants:
- If no list of files is provided to `deploy`, it will first make a GET request to discover what files are on the server. From this it can determine if any local files should be deleted.
- If a list of files it provided to `deploy`, then it does not make the GET request. 
To compare local checksums against remote checksums, we now need to make the GET request for both these situations.
Note: There are also fixes to no longer show skipped files when in non-verbose mode.
=> Skip uploads if checksums match

cmd/get.go, cmd/theme.go, docs/commands/index.md, docs/configuration/index.md, src/cmdutil/_testdata/config.yml, src/cmdutil/util.go, src/cmdutil/util_test.go, src/env/_testdata/projectdir/valid_config.yml, src/env/conf_test.go, src/env/env.go, src/env/env_test.go, src/shopify/theme_client.go
fixes #699
fixes #670
This makes a tighter constraint on the theme ID and makes the tool a lot safer for changing live themes.
- If a theme ID was not provided or the string 'live' was provided as a theme ID, themekit would assume the live theme was to be operated on.
- If the theme was the live theme, a warning would be displayed but continue its operation.
- Theme IDs are strictly required. There is an error if the theme ID is blank. 
- There is an error raised if the tool tries changing the live theme
- if the flag `--allow-live` is passed then the tool will be able to change the live theme.
I think technically this is a breaking change so it should require us to make a major version change
=> Making theme ID required to make it harder to edit a live theme

.gitignore, docs/_includes/sidebar.html, docs/index.md
This PR updates a broken ID link in the navigation.
It also adds `.jekyll-cache` to gitignore for cleaner commit workflow.
=> fix broken link in nav

src/shopify/theme_client.go, src/shopify/theme_client_test.go
We expect checksums to be part of the 2020-10 release. Until then, we'll need to point to the unstable version of the API.
=> Use unstable API version for checksums support

go.mod, go.sum, src/httpify/client.go, src/httpify/client_test.go, src/ratelimiter/rate_limiter.go, src/ratelimiter/rate_limiter_test.go, src/shopify/theme_client.go
fixes #715
fixes #665
This will solve a few errors with asset requests, more specifically timeouts but also hopefully speed up requests during actions like `deploy` especially for plus merchants. 
Themekit was throttled directly to 2 requests per second to just try to ensure that a 429 was never received. 
I have added strategy to throtting.
- Changes to the rate limiter
- made it nicer to specify requests per second (for myself)
- using a (x)-std lib library for throttling instead to get the bonus of bursts
- added `ResetAfter` to halt everything until a future time.
- Changes to the http client
- rate limiter is not limiting to 4 requests per second (the plus limit)
- if we get a 429 we record the time that we should resume and the request is set to retry
- all requests are held until …
=> Adding Retries and improved throttling to HTTP requests

cmd/notify_adapters.go, cmd/notify_adapters_test.go, cmd/theme.go, cmd/watch.go, cmd/watch_test.go, src/cmdutil/util.go, src/cmdutil/util_test.go, src/file/watcher.go, src/file/watcher_test.go
This implements @felipebrahm proposal from last week.
- removed notification functionality from the file watcher
- added the notification functionality to come after perform operations in the watch command
- implemented an adapter pattern for 
- noop: no notify setting
- url: for url as the notify setting
- file: for a filepath as the notify setting
- Pass in a notification adapter to the watch command depending on the notification setting.
- notify after http call https://github.com/Shopify/themekit/pull/750
- notify webhook https://github.com/felipebrahm/themekit/commit/538de9ddfab3f41b1345082effed633e2f11e62d
- Issue https://github.com/Shopify/themekit/issues/749
=> Changing notification system

cmd/download.go, cmd/open.go, cmd/watch.go, src/env/env.go, src/env/env_test.go
We got some feedback from beta testing that the `--allow-live` flag is not really needed on the open and download commands so this PR automatically adds the flag to those commands so that they are able to do these actions.
It also occurred to me that it would make things nicer if we added output about the `live` config from the past, so I added a specific error for a live configuration.
=> Automatically allowing live on open and download

changelog.txt, choco/themekit.nuspec, choco/tools/chocolateyinstall.ps1, docs/_config.yml, src/release/release.go
Release steps:
then run `make md5s` to generate the checksums for the new files. Add these to the `docs/_config.yml`
file as well.
of an update so they can release a new version.
=> Prepare 1.1.0 release

cmd/new.go, src/env/conf.go
fixes #766 
This will fix the new command requiring a theme_id.
It also just cleans up a small bit of code that was repeated in conf while I was looking how to make these patches more official. I might be able to make these patches more official in the future.
=> Patch for the new command

changelog.txt, docs/_config.yml, src/release/release.go
New release due to https://github.com/Shopify/themekit/pull/767
----
then run `make md5s` to generate the checksums for the new files. Add these to the `docs/_config.yml`
file as well.
of an update so they can release a new version.
=> Prepare v1.1.1 release

docs/commands/index.md
We need to add docs for the new notify flag accepting a URL
=> Update docs for watch

choco/themekit.nuspec, choco/tools/chocolateyinstall.ps1
We already released v1.1.1 but not yet for Chocolately.
=> Prepare Chocolatey v1.1.1 release

CONTRIBUTING.md, docs/index.md
* Make it clear that the Theme Kit Arch Linux package is maintained by a third party, and not Shopify.
* Move the responsibility of monitoring Theme Kit for updates to the third-party package maintainer. This helps to shorten the long list of manual steps currently needed for each release. For a recent release, the maintainer made an update before we had notified, so it seems they are already monitoring it.
=> Update Arch Linux notes

README.md, docs/index.md
Finding places where Theme Kit is spelled without spaces or capitals and replacing. This also makes it consistent with how we write it on the public site.
=> Updating places where Theme Kit is spelled inconsistently

.github/ISSUE_TEMPLATE/bug_report.md
@paulomarg and I have both misread the example version number in tickets, let's change this to prevent that happening again.
=> Update template to prevent version confusion

src/httpify/client.go, src/httpify/client_test.go
fixes #790 
fixes #801 
fixes #810 
Re-evaluating the retry mechanism, I realized that there was a fault in the if statements where the attempt count would only get incremented on timeouts and not for all other errors like 500s.
Here is the logic now
- if non-retryable http status (success or otherwise), return (100 =< code <= 428)
- if 499 then use retry-after header to block all requests until after the time limit then continue without incrementing attempt because this is not an error. I don't want to fail out of uploads because of 499s
- If request failed with host error, its fatal, return
- Otherwise, increment attempt and try again
=> Fixing hanging uploads

src/httpify/client_test.go
Fixes #814 
We had some tests that intermittently failed because we were running the HTTP client with a 1ms timeout, and sometimes that wasn't enough to deal with the test requests in time.
This PR increases that timeout to 5ms, which seems to make it so the tests pass reliably.
=> Increase timeout of test HTTP client

src/env/env.go, src/httpify/client.go, src/httpify/client_test.go, src/ratelimiter/rate_limiter.go, src/release/release.go
will-fix #801 
With my experience doing highly concurrent http request in Go, I know that the default client has issues managing idle connection management, especially if it has no bounds on growth. I believe that this may be the issue that is causing the requests to hang. I debugged the hanging issues and the hang was actually happening on the request.
@MuhammadFarag I pinged you because you made the last tweaks to CH http client
=> Http Client tweaks to idle conns to prevent hangs in connections

docs/index.md
We set execute permission in the Python setup script but it's currently missing from the manual steps.
=> Add Linux permissions step

docs/index.md
The Homebrew distribution only includes a Darwin (Mac) binary so won't work on Linux.
=> Add note about Homebrew for Linux

docs/faq/index.md
I noticed that the uninstall instructions are assuming a manual installation, but most people are probably using Homebrew.
=> Add Homebrew uninstall instructions

docs/scripts/install.py
fixes #725
The installation script only allowed python2 and not python3 but this simple change allows both versions for installation.
Works for both python2 and python3:
=> Allowing python 3 usage

changelog.txt, cmd/deploy.go, cmd/download.go, cmd/download_test.go, cmd/theme.go, cmd/theme/main.go, cmd/watch.go, src/cmdutil/summary.go, src/cmdutil/summary_test.go, src/cmdutil/util.go, src/cmdutil/util_test.go, src/colors/colors.go, src/file/watcher.go
fixes #823 
fixes #822 
fixes #738 
This PR is an effort to collect runtime file operations data and present them at the end of the runtime. This will have multiple effects
- Changed skipped color to cyan instead
- Showing the summary (download, upload, deleted, skipped, errors) of changes for `deploy` `remove` `download` `get` `new` with a consistent theme between all.
- Showing a count of errors
- Showing an output of the errors that were encountered
- Collecting error data to return status (still need to do) Currently themekit only sets error status if an error is returned however we need a way to return a general error if any were encountered during runtime
- Set error status when errors happened during file changes
- Make all fatal errors red.
Updated Screenshot:
=> Action summary and return status

changelog.txt, cmd/configure.go, cmd/download.go, cmd/get.go, cmd/get_test.go, cmd/theme.go, docs/commands/index.md, src/cmdutil/util.go, src/cmdutil/util_test.go
fixes #785 
This adds a `--live` flag to `get` `download` and `config` so that the live theme is easily access from commands that only pull data. It prefills the theme ID for those commands.
=> Adding a Live flags to allow easy access to downloading live theme

changelog.txt, cmd/open.go, cmd/open_test.go, cmd/theme.go, docs/commands/index.md, src/cmdutil/util.go
fixes #820 
Paired with @carmelal 
Adds `--hidepb` to `theme open` to automatically hide the preview bar.
=> Hide PB on open

.travis.yml, changelog.txt, src/httpify/client.go, src/ratelimiter/rate_limiter.go, src/ratelimiter/rate_limiter_test.go
related #801 
This changes our rate limiter into a smart circuit breaking throttle gate. What this means functionally that:
- The request rate is limited to 4 per/second with bursts of 4 requests allowed
- When we get a 429 response, we cancel all inflight requests and they are all paused for the Retry-After value
- the allotted time is waited on
- The cancelled requests are started again
- The original request with the 429 response is restarted.
- None of these retries are counted against the http retry mechanism as they are not an error response from shopify or an error in the asset.
Tests still need to be updated a little bit.
=> Smarter Throttle Gate

changelog.txt, src/shopify/theme_client.go, src/shopify/theme_client_test.go, src/shopify/unmarshal.go, src/shopify/unmarshal_test.go
Related to #631
Right now, while unmarshalling responses, if the response is not JSON, then themekit will return an unhelpful error of `malformed response` While themekit does not really know what happened, and we have no way of knowing, we can add some more information to help analyze the issue.
To the main `unmarshalResponse` method that the theme client uses, this adds
- http response status codes to the error messages. This should give us more insight into what the actual response is (500+ status codes)
- flushes the response body to a tempfile, so that it can be included in issue debugging. 
- outputs a path to the tempfile in the error message if flushing was successful.
=> Adding more feedback while unmarshalling responses

theme-template/assets/application.css.liquid
Since Shopify is going to deprecate Sass for Shopify themes, the default stylesheet should change to CSS.
https://www.shopify.com/partners/blog/deprecating-sass
@tanema @chrisbutcher
=> Change default theme stylesheet from Sass to CSS

changelog.txt, cmd/get.go
fixes #858 
While changing get, the them ID shim was removed, making the list action require a theme ID, this removes that requirement
=> Fake theme ID in get command for listing

changelog.txt, src/httpify/client.go
fixes #857 
In previous work, I added in a bunch of arbitrary timeouts, this was because I wanted requests to fail faster if there was an issue. This however was misguided because the actual solution was cancelling the requests. The timeouts were also copied over from our webhook delivery service that I worked on and themekit and that service have vastly different request requirements. Webhook delivery requires fast completion on delivery, however themekit is used to uploading very large files that need more time to complete, so this was done in error.
I have just removed all of these timeouts as the defaults are either pretty large or no timeout is set at all. There is still a general overall request timeout so that does not mean requests will get stuck.
This fix has been confirmed in …
=> Taking out my arbitrary timeouts

changelog.txt, cmd/watch.go, cmd/watch_test.go
fixes #855 
Currently pressing ctrl-C while watch is running will not terminate its execution. This is because the signal channel is unbuffered so signal.Notify cannot write to the channel until it is read and it gets starved in the select statement. I added a buffer of 1 which allows it to be cancelled.
=> Allow watch early exit

docs/scripts/install.py
fixes #856 
The past change to the install script was cleaner but I thought `six.moves` was a stdlib and it turns out that is incorrect and the script should not have any deps, so I have changed back to this ugly version that does the version switch itself.
=> Remove six lib from install script

changelog.txt, go.mod, go.sum, src/file/watcher.go, src/file/watcher_test.go
fixes #664
In previous versions, I watched each individual project directory however that created problems with creating new directories while the command run, and they were not tracked. Next step I took was to just watch all recursively and filter the events to just the project directories. This worked except, those with node_modules folders found that this caused their laptop to melt. 
This version now watched the root directory and project directories and does not filter out directory events. Now when a new directory is created, it will catch that event and start watching it, any deleted directories are discarded.
This should clear up the CPU issues.
I updated the dependency which allowed me to not have to parse new and old paths, and I am happy whenever I get to delete string parsing …
=> CPU usage optimization in watch command

src/file/watcher.go, src/file/watcher_test.go
fixes #885
The file watcher would only originally catch directory events if they were the first event before the event buffer was started. This was because normally the event buffer is used to catch duplicate events or quick events like swap files which move and write at the same time. However there are some editors that touch the directory along with the file that was edited so the file edit event would come first, and the mod of the directory second, causing themekit to miss that event and it getting flushed through the rest of the system. 
The directory event handling has been moved to the event translation step so that it will convert directory events into noops. This is a more central place to do this.
=> Fixing folder events in file watcher

Makefile, RELEASING.md, changelog.txt, src/release/release.go
I release 1.1.6 for the doc changes but forgot to include the changelog updates and change the version number on main first. This was a mess.
After releasing in this new process. I have updated the releasing document to reflect what I had to do, as well as changed makefile commands to make releasing easier.
You can now see what the new releases look like with the included sums https://github.com/Shopify/themekit/releases/tag/v1.1.6
=> finishing up messy release

docs/commands/index.md, docs/configuration/index.md, docs/development/index.md, docs/faq/index.md
- Adds redirects for deep links associated with Theme Kit pages (configuration reference, command reference, developing theme kit, and troubleshooting)
- Relates to https://github.com/Shopify/themekit/issues/899
=> Add redirects for deep links

docs/ignores/index.md
- Redirects https://shopify.github.io/themekit/ignores/ to the configuration reference on shopify.dev.
- Relates to https://github.com/Shopify/themekit/issues/899 and https://github.com/Shopify/shopify-dev/issues/5032
=> Redirect https://shopify.github.io/themekit/ignores/

CONTRIBUTING.md, dev.yml
This allows Shopifolk to set up the app for development by running `dev up`.
=> Add dev.yml

src/httpify/client.go, src/httpify/client_test.go
**Description**
Themekit needs to make requests either to ThemeKit Access or to Shopify depending on the type of password token that user has. This should have no effect for existing Themekit users.
The solution checks whether user token starts with an identifiable prefix `shptka_` and redirect all requests to the Theme Kit Access server.
**Additional context**
The issue is related to the new public ThemeKit Access app development.
=> Add redirect to ThemeKit Access when password prefix matches pattern

cmd/theme.go, src/cmdutil/util.go, src/httpify/client.go, src/util/themekit_access.go, src/util/themekit_access_test.go
The Theme Kit Access app is in beta now. When we move to GA, we want to encourage developers to make the switch by adding messaging to the Theme Kit CLI. This PR adds that message and a flag to be able to suppress it.
Part of https://github.com/Shopify/themekit-access/issues/147
=> Add messaging Theme Kit Access messaging and flag to suppress it

changelog.txt, cmd/theme.go, src/httpify/client.go, src/httpify/client_test.go, src/util/themekit_access.go, src/util/themekit_access_test.go
Part of https://github.com/Shopify/shopify-cli-planning/issues/364
=> Rename Theme Kit Access references to Theme Access

Makefile, changelog.txt, choco/themekit.nuspec, choco/tools/chocolateyinstall.ps1, dev.yml, docs/scripts/install.py, scripts/install.py, src/release/release.go, src/release/release_test.go
Besides updating the version and changelog, I had to make 2 additional changes:
- Upgrade Go, because [1.13 is no longer supported from Homebrew since July](https://formulae.brew.sh/formula/go@1.13)
- Drop support for darwin-386, as [Go doesn't support it since 1.15](https://go.dev/doc/go1.15#386)
=> Release 1.3.1
